// Code generated by protoc-gen-go. DO NOT EDIT.
// source: person.proto

package main

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Person_Sex int32

const (
	Person_male   Person_Sex = 0
	Person_female Person_Sex = 1
)

var Person_Sex_name = map[int32]string{
	0: "male",
	1: "female",
}

var Person_Sex_value = map[string]int32{
	"male":   0,
	"female": 1,
}

func (x Person_Sex) String() string {
	return proto.EnumName(Person_Sex_name, int32(x))
}

func (Person_Sex) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_4c9e10cf24b1156d, []int{0, 0}
}

type Person struct {
	Id                   int32         `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name                 string        `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Age                  int32         `protobuf:"varint,3,opt,name=age,proto3" json:"age,omitempty"`
	Money                float32       `protobuf:"fixed32,4,opt,name=money,proto3" json:"money,omitempty"`
	Car                  []string      `protobuf:"bytes,5,rep,name=car,proto3" json:"car,omitempty"`
	Phone                *Person_Phone `protobuf:"bytes,6,opt,name=phone,proto3" json:"phone,omitempty"`
	Sex                  Person_Sex    `protobuf:"varint,7,opt,name=sex,proto3,enum=main.Person_Sex" json:"sex,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *Person) Reset()         { *m = Person{} }
func (m *Person) String() string { return proto.CompactTextString(m) }
func (*Person) ProtoMessage()    {}
func (*Person) Descriptor() ([]byte, []int) {
	return fileDescriptor_4c9e10cf24b1156d, []int{0}
}

func (m *Person) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Person.Unmarshal(m, b)
}
func (m *Person) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Person.Marshal(b, m, deterministic)
}
func (m *Person) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Person.Merge(m, src)
}
func (m *Person) XXX_Size() int {
	return xxx_messageInfo_Person.Size(m)
}
func (m *Person) XXX_DiscardUnknown() {
	xxx_messageInfo_Person.DiscardUnknown(m)
}

var xxx_messageInfo_Person proto.InternalMessageInfo

func (m *Person) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *Person) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Person) GetAge() int32 {
	if m != nil {
		return m.Age
	}
	return 0
}

func (m *Person) GetMoney() float32 {
	if m != nil {
		return m.Money
	}
	return 0
}

func (m *Person) GetCar() []string {
	if m != nil {
		return m.Car
	}
	return nil
}

func (m *Person) GetPhone() *Person_Phone {
	if m != nil {
		return m.Phone
	}
	return nil
}

func (m *Person) GetSex() Person_Sex {
	if m != nil {
		return m.Sex
	}
	return Person_male
}

type Person_Phone struct {
	Number               string   `protobuf:"bytes,1,opt,name=number,proto3" json:"number,omitempty"`
	Type                 string   `protobuf:"bytes,2,opt,name=type,proto3" json:"type,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Person_Phone) Reset()         { *m = Person_Phone{} }
func (m *Person_Phone) String() string { return proto.CompactTextString(m) }
func (*Person_Phone) ProtoMessage()    {}
func (*Person_Phone) Descriptor() ([]byte, []int) {
	return fileDescriptor_4c9e10cf24b1156d, []int{0, 0}
}

func (m *Person_Phone) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Person_Phone.Unmarshal(m, b)
}
func (m *Person_Phone) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Person_Phone.Marshal(b, m, deterministic)
}
func (m *Person_Phone) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Person_Phone.Merge(m, src)
}
func (m *Person_Phone) XXX_Size() int {
	return xxx_messageInfo_Person_Phone.Size(m)
}
func (m *Person_Phone) XXX_DiscardUnknown() {
	xxx_messageInfo_Person_Phone.DiscardUnknown(m)
}

var xxx_messageInfo_Person_Phone proto.InternalMessageInfo

func (m *Person_Phone) GetNumber() string {
	if m != nil {
		return m.Number
	}
	return ""
}

func (m *Person_Phone) GetType() string {
	if m != nil {
		return m.Type
	}
	return ""
}

type Group struct {
	Person               []*Person `protobuf:"bytes,1,rep,name=person,proto3" json:"person,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *Group) Reset()         { *m = Group{} }
func (m *Group) String() string { return proto.CompactTextString(m) }
func (*Group) ProtoMessage()    {}
func (*Group) Descriptor() ([]byte, []int) {
	return fileDescriptor_4c9e10cf24b1156d, []int{1}
}

func (m *Group) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Group.Unmarshal(m, b)
}
func (m *Group) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Group.Marshal(b, m, deterministic)
}
func (m *Group) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Group.Merge(m, src)
}
func (m *Group) XXX_Size() int {
	return xxx_messageInfo_Group.Size(m)
}
func (m *Group) XXX_DiscardUnknown() {
	xxx_messageInfo_Group.DiscardUnknown(m)
}

var xxx_messageInfo_Group proto.InternalMessageInfo

func (m *Group) GetPerson() []*Person {
	if m != nil {
		return m.Person
	}
	return nil
}

func init() {
	proto.RegisterEnum("main.Person_Sex", Person_Sex_name, Person_Sex_value)
	proto.RegisterType((*Person)(nil), "main.Person")
	proto.RegisterType((*Person_Phone)(nil), "main.Person.Phone")
	proto.RegisterType((*Group)(nil), "main.Group")
}

func init() { proto.RegisterFile("person.proto", fileDescriptor_4c9e10cf24b1156d) }

var fileDescriptor_4c9e10cf24b1156d = []byte{
	// 252 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x54, 0x90, 0xcf, 0x4a, 0x03, 0x31,
	0x10, 0xc6, 0xcd, 0x66, 0x13, 0xed, 0xb4, 0x94, 0x65, 0x10, 0x09, 0x7a, 0x09, 0x8b, 0x87, 0x5c,
	0xdc, 0xc3, 0xf6, 0x21, 0xbc, 0x96, 0xf4, 0x09, 0xb6, 0x76, 0xd4, 0x05, 0xf3, 0x87, 0xb4, 0x85,
	0xed, 0x0b, 0xf8, 0xdc, 0x92, 0x6c, 0x11, 0xbd, 0xfd, 0x26, 0xdf, 0x17, 0xe6, 0xc7, 0xc0, 0x2a,
	0x52, 0x3a, 0x06, 0xdf, 0xc5, 0x14, 0x4e, 0x01, 0x6b, 0x37, 0x8c, 0xbe, 0xfd, 0xae, 0x40, 0x6e,
	0xcb, 0x33, 0xae, 0xa1, 0x1a, 0x0f, 0x8a, 0x69, 0x66, 0x84, 0xad, 0xc6, 0x03, 0x22, 0xd4, 0x7e,
	0x70, 0xa4, 0x2a, 0xcd, 0xcc, 0xc2, 0x16, 0xc6, 0x06, 0xf8, 0xf0, 0x41, 0x8a, 0x97, 0x52, 0x46,
	0xbc, 0x07, 0xe1, 0x82, 0xa7, 0x8b, 0xaa, 0x35, 0x33, 0x95, 0x9d, 0x87, 0xdc, 0x7b, 0x1b, 0x92,
	0x12, 0x9a, 0x9b, 0x85, 0xcd, 0x88, 0x06, 0x44, 0xfc, 0x0c, 0x9e, 0x94, 0xd4, 0xcc, 0x2c, 0x7b,
	0xec, 0xf2, 0xfa, 0x6e, 0x5e, 0xdd, 0x6d, 0x73, 0x62, 0xe7, 0x02, 0xb6, 0xc0, 0x8f, 0x34, 0xa9,
	0x5b, 0xcd, 0xcc, 0xba, 0x6f, 0xfe, 0xf5, 0x76, 0x34, 0xd9, 0x1c, 0x3e, 0x6e, 0x40, 0x94, 0x3f,
	0xf8, 0x00, 0xd2, 0x9f, 0xdd, 0x9e, 0x52, 0x11, 0x5f, 0xd8, 0xeb, 0x94, 0xe5, 0x4f, 0x97, 0xf8,
	0x2b, 0x9f, 0xb9, 0x7d, 0x02, 0xbe, 0xa3, 0x09, 0xef, 0xa0, 0x76, 0xc3, 0x17, 0x35, 0x37, 0x08,
	0x20, 0xdf, 0xa9, 0x30, 0x6b, 0x5f, 0x40, 0xbc, 0xa6, 0x70, 0x8e, 0xf8, 0x0c, 0x72, 0xbe, 0x93,
	0x62, 0x9a, 0x9b, 0x65, 0xbf, 0xfa, 0x6b, 0x60, 0xaf, 0xd9, 0x5e, 0x96, 0x23, 0x6e, 0x7e, 0x02,
	0x00, 0x00, 0xff, 0xff, 0x62, 0x03, 0x85, 0xc5, 0x54, 0x01, 0x00, 0x00,
}
